# Generated by Django 3.0.8 on 2020-07-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='image_field',
        ),
    ]
