# Generated by Django 3.1 on 2020-08-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Register activated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_at',
            field=models.DateTimeField(help_text='0000-00-00 00:00:00 форматтай байна', null=True, verbose_name='Start_at'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='state',
            field=models.CharField(choices=[('started', 'Сургалт эхэлсэн'), ('done', 'Сургалт дууссан')], default='started', max_length=100, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Youtubecode'),
        ),
    ]
