# Generated by Django 3.1 on 2020-11-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='start_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='state',
        ),
        migrations.AddField(
            model_name='course',
            name='start_at',
            field=models.DateTimeField(help_text='0000-00-00 00:00:00 форматтай байна', null=True, verbose_name='Start_at'),
        ),
        migrations.AddField(
            model_name='course',
            name='state',
            field=models.CharField(choices=[('started', 'Lesson started'), ('done', 'Lesson over')], default='started', max_length=100, verbose_name='State'),
        ),
    ]
