# Generated by Django 3.1 on 2020-11-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201106_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.CharField(choices=[('Эхэлсэн', 'Lesson started'), ('Дууссан', 'Lesson over'), ('Хадаглагдсан', 'Хичээл хадгалагдсан')], default='started', max_length=100, verbose_name='State'),
        ),
    ]
