# Generated by Django 3.1 on 2020-11-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201106_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.CharField(choices=[('1', 'Lesson started'), ('2', 'Lesson over'), ('3', 'Хичээл хадгалагдсан')], default='1', max_length=100, verbose_name='State'),
        ),
    ]
