# Generated by Django 3.1 on 2020-11-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201106_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.CharField(choices=[('Хичээл эхэлсэн', 'Lesson started'), ('Хичээл дууссан', 'Lesson over'), ('Хичээл хадгалагдсан', 'Хичээл хадгалагдсан')], default='1', max_length=100, verbose_name='State'),
        ),
    ]
