# Generated by Django 3.1 on 2020-11-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20201106_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.CharField(choices=[('started', 'Lesson started'), ('over', 'Lesson over'), ('archive', 'Хичээл хадгалагдсан')], default='1', max_length=100, verbose_name='State'),
        ),
    ]
