# Generated by Django 3.1 on 2020-11-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20201106_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.CharField(choices=[('started', 'Хичээл эхэлсэн'), ('over', 'Хичээл дууссан'), ('archive', 'Хичээл хадгалагдсан')], default='1', max_length=100, verbose_name='State'),
        ),
    ]
