# Generated by Django 3.1 on 2020-08-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200831_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=250, null=True, verbose_name='Хариулт'),
        ),
    ]
