# Generated by Django 3.1 on 2020-11-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20201109_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pdf_file_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Файлын нэр'),
        ),
    ]
