# Generated by Django 3.1 on 2020-09-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200831_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='embedurl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
