# Generated by Django 3.1 on 2020-09-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lesson_embedurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
