# Generated by Django 3.1 on 2020-09-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200914_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'Course', 'verbose_name_plural': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ['title'], 'verbose_name': 'Course category', 'verbose_name_plural': 'Course category'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['title'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lesson'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subject'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='state',
            field=models.CharField(choices=[('started', 'Lesson started'), ('done', 'Lesson over')], default='started', max_length=100, verbose_name='State'),
        ),
    ]
