# Generated by Django 3.1 on 2021-06-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
