# Generated by Django 3.1 on 2020-09-14 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lesson_embedurl'),
        ('quiz', '0002_quiz_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_list', to='courses.lesson', verbose_name='Lesson'),
        ),
    ]
