# Generated by Django 3.1 on 2020-09-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200914_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='url',
            new_name='slug',
        ),
    ]
