# Generated by Django 3.1 on 2020-09-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200914_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='slug',
            new_name='url',
        ),
    ]
