# Generated by Django 3.1 on 2020-09-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200914_1149'),
        ('quiz', '0006_auto_20200914_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson', verbose_name='Lesson'),
        ),
    ]
