# Generated by Django 3.0.8 on 2020-08-12 06:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=255, verbose_name='Lastname')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('Phone', models.CharField(default='', max_length=10)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Request Lesson',
                'verbose_name_plural': 'Request Lesson',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=900, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Human resource',
                'verbose_name_plural': 'Human resources',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('Phone', models.CharField(default='', max_length=10)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Холбоо барих',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ListTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=128, null=True, verbose_name='Text')),
                ('open_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Hr', verbose_name='Open job')),
            ],
            options={
                'verbose_name': 'List title ',
                'verbose_name_plural': 'List titles',
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', ckeditor.fields.RichTextField(null=True)),
                ('list_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ListTitle', verbose_name='List title')),
            ],
            options={
                'verbose_name': 'List Item ',
                'verbose_name_plural': 'List Items',
            },
        ),
    ]
