# Generated by Django 3.0.8 on 2020-08-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='hello',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
