# Generated by Django 3.1 on 2020-08-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_listitem_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='slug',
            field=models.SlugField(default='', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
