# Generated by Django 3.1 on 2020-08-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_hr_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='created_at',
            field=models.DateField(auto_now=True, auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='hr',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline date '),
        ),
    ]
