# Generated by Django 3.1 on 2020-09-11 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200825_2125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
