# Generated by Django 3.1 on 2020-09-11 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
