# Generated by Django 3.1 on 2020-09-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.FileField(upload_to='/media/anket/', verbose_name='Questionnaire')),
            ],
        ),
    ]
