# Generated by Django 3.1 on 2020-09-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire',
            field=models.FileField(upload_to='media/anket/', verbose_name='Questionnaire'),
        ),
    ]
