# Generated by Django 3.1 on 2020-09-16 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200916_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='questionnaire',
            new_name='anket',
        ),
    ]
