# Generated by Django 3.1 on 2020-09-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200922_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['name'], 'verbose_name': 'Contact'},
        ),
    ]
