# Generated by Django 3.1 on 2020-11-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20200922_1922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Холбоо барих'},
        ),
    ]
