# Generated by Django 3.2.7 on 2021-12-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20201105_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Хэлний нэр')),
                ('code', models.CharField(max_length=5, verbose_name='Хэлний код')),
            ],
            options={
                'verbose_name': 'Хэл',
                'verbose_name_plural': 'Хэл',
                'ordering': ['name'],
            },
        ),
    ]
