# Generated by Django 3.2.7 on 2021-12-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
