# Generated by Django 3.0.8 on 2020-07-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('picture', models.FileField(upload_to='media/gallery/')),
            ],
            options={
                'verbose_name': 'Gallery',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=600, verbose_name='Content')),
                ('profile', models.FileField(upload_to='media/testimonails/profile')),
                ('person', models.CharField(max_length=55, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Testimonail',
                'verbose_name_plural': 'Testimonails',
            },
        ),
    ]
