# Generated by Django 3.1 on 2020-12-18 04:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Advice title',
                'verbose_name_plural': 'Advice title',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(max_length=550, null=True, verbose_name='Баннер зурагын хайлтын системд туслах тэскт')),
                ('photo', models.FileField(upload_to='media/banners', verbose_name='Баннер зураг орох')),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Banner picture',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='BannerVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=255, verbose_name='Banner video')),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(blank=True, null=True, upload_to='counter', verbose_name='Арын зураг')),
                ('title', models.CharField(max_length=255, verbose_name='Гарчиг')),
                ('icon', models.CharField(blank=True, help_text='icon-check-mark, гэх мэт icon-ууд оруулж өгнө', max_length=55, null=True, verbose_name='Icon бичнэ')),
                ('number', models.CharField(help_text='250сая гэсэн байдлаар тоог оруулна', max_length=55, verbose_name='Тоо тоолуур')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Байрших байрлал')),
            ],
            options={
                'verbose_name': 'Тоолуур',
                'verbose_name_plural': 'Тоолуур',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Гарчиг хэсэг')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тайлбар хэсэг')),
                ('image', models.FileField(upload_to='media/gallery')),
            ],
            options={
                'verbose_name': 'Зургын сан',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LeftFeaturedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_emonos', models.CharField(max_length=255)),
                ('picture', models.FileField(upload_to='media/Featuredproduct/')),
            ],
            options={
                'verbose_name': 'Зүүн танилцуулга бүтээгдэхүүн',
                'ordering': ['link_to_emonos'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/partner', verbose_name='Хамтрагч байгуулгын зураг')),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Хамтрагч байгуулгын зураг',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='RightFeaturedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_emonos', models.CharField(max_length=255)),
                ('picture', models.FileField(upload_to='media/Featuredproduct/')),
            ],
            options={
                'verbose_name': 'Баруун танилцуулга бүтээгдэхүүн',
                'ordering': ['link_to_emonos'],
            },
        ),
        migrations.CreateModel(
            name='Testimonail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('profile', models.FileField(upload_to='media/testimonails/profile')),
                ('person', models.CharField(max_length=55, verbose_name='Guest')),
                ('job', models.CharField(default='', max_length=128, verbose_name='Guest job')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonial',
            },
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField()),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content')),
                ('author', models.CharField(max_length=128, verbose_name='Author')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='advice_image')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.advicecategory')),
            ],
            options={
                'verbose_name': 'Advice',
                'verbose_name_plural': 'Advice',
                'ordering': ['-created_on'],
            },
        ),
    ]
