# Generated by Django 3.0.8 on 2020-07-31 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Advice category',
                'verbose_name_plural': 'Advice categories',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.CharField(max_length=500, verbose_name='Text')),
                ('author', models.CharField(max_length=128, verbose_name='Author')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.AdviceCategory')),
            ],
            options={
                'verbose_name': 'Advice',
                'verbose_name_plural': 'Advices',
                'ordering': ['-created_on'],
            },
        ),
    ]
