# Generated by Django 3.1 on 2021-08-23 03:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(max_length=550, null=True, verbose_name='Баннер зурагын хайлтын системд туслах тэскт')),
                ('photo', models.FileField(upload_to='media/banners', verbose_name='Баннер зураг орох')),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Бидний тухай хуудас баннер',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DirectorsGreetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/zahiral', verbose_name='Захиралын зураг')),
                ('context', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контэнт')),
            ],
            options={
                'verbose_name': 'Захиралын мэндчилгээ',
                'verbose_name_plural': 'Захиралын мэндчилгээ',
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Танилцуулга')),
            ],
            options={
                'verbose_name': 'Компаны танилцуулга',
                'verbose_name_plural': 'Компаны танилцуулга',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Эрхэм зорилго')),
            ],
            options={
                'verbose_name': 'Эрхэм зорилго',
                'verbose_name_plural': 'Эрхэм зорилго',
            },
        ),
    ]
