# Generated by Django 3.0.8 on 2020-07-31 01:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_advice_advicecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advice',
            name='text',
        ),
        migrations.AddField(
            model_name='advice',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='testimonail',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
