# Generated by Django 3.1 on 2021-08-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_banneraboutus_directorsgreetings_introduction_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/featurebox', verbose_name='Зураг')),
                ('title', models.CharField(max_length=500, verbose_name='Гарчиг')),
                ('context', models.TextField(verbose_name='Контэнт')),
            ],
            options={
                'verbose_name': 'Бидний тухай хэсэгын карт',
                'verbose_name_plural': 'Бидний тухай хэсэгын карт',
            },
        ),
    ]
