# Generated by Django 3.1 on 2021-08-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_aboutuscards'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(max_length=550, null=True, verbose_name='Баннер зурагын хайлтын системд туслах тэскт')),
                ('photo', models.FileField(upload_to='media/hrbanner', verbose_name='Баннер зураг орох')),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'HR хуудас баннер',
                'ordering': ['position'],
            },
        ),
    ]
