# Generated by Django 3.0.8 on 2020-07-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200731_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonail',
            name='job',
            field=models.CharField(default='', max_length=128, verbose_name='Job'),
        ),
    ]
