# Generated by Django 3.0.8 on 2020-07-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_testimonail_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/partner', verbose_name='Image')),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Partners',
                'ordering': ['-position'],
            },
        ),
    ]
