# Generated by Django 3.1 on 2021-08-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_aboutuscards_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuscards',
            options={'ordering': ['position'], 'verbose_name': 'Бидний тухай хэсэгын карт', 'verbose_name_plural': 'Бидний тухай хэсэгын карт'},
        ),
        migrations.AddField(
            model_name='aboutuscards',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
