# Generated by Django 3.1 on 2020-09-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('ad', models.CharField(max_length=255)),
                ('emonos', models.CharField(max_length=255)),
                ('picture', models.FileField(upload_to='media/Featuredproduct/')),
            ],
            options={
                'verbose_name': 'Featured Product',
                'ordering': ['title'],
            },
        ),
    ]
