# Generated by Django 3.1 on 2020-09-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_featuredproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='picture',
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.FileField(default='', upload_to='media/gallery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gallery'),
        ),
    ]
