# Generated by Django 3.1 on 2021-08-24 14:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210824_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hrcontent', verbose_name='Зураг')),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Хүний нөөцийн хуудас контент',
                'verbose_name_plural': 'Хүний нөөцийн хуудас контент',
                'ordering': ['position'],
            },
        ),
    ]
