# Generated by Django 3.1 on 2021-08-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_hrcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrbanner',
            options={'ordering': ['position'], 'verbose_name': 'Хүний нөөц хуудас баннер'},
        ),
    ]
