# Generated by Django 3.1 on 2020-09-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200925_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Counter number')),
                ('content', models.CharField(max_length=255, verbose_name='Counter number description')),
                ('position', models.IntegerField()),
                ('picture', models.FileField(upload_to='media/counter')),
            ],
            options={
                'verbose_name': 'Counter',
                'ordering': ['position'],
            },
        ),
    ]
