# Generated by Django 3.1 on 2020-10-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(max_length=550, null=True, verbose_name='Banner')),
                ('photo', models.FileField(upload_to='media/banners', verbose_name='Banner photo')),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Banner',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='BannerVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=255, verbose_name='Banner Video')),
            ],
        ),
    ]
