# Generated by Django 3.1 on 2021-08-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210824_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrcontent',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Гарчиг'),
        ),
    ]
