# Generated by Django 3.1 on 2020-11-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_banner_bannervideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
