# Generated by Django 3.1 on 2021-08-24 15:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_hrcontent_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taniltsuulga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Гарчиг')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='taniltsuulga', verbose_name='Зураг')),
            ],
            options={
                'verbose_name': 'Бидний тухай - Танилцуулга',
                'verbose_name_plural': 'Бидний тухай - Танилцуулга',
            },
        ),
    ]
