# Generated by Django 3.1 on 2021-08-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_taniltsuulga'),
    ]

    operations = [
        migrations.AddField(
            model_name='taniltsuulga',
            name='gmp',
            field=models.ImageField(blank=True, null=True, upload_to='taniltsuulga', verbose_name='Эм үйлдвэрлэл'),
        ),
        migrations.AddField(
            model_name='taniltsuulga',
            name='lab',
            field=models.ImageField(blank=True, null=True, upload_to='taniltsuulga', verbose_name='Лаборатори'),
        ),
        migrations.AddField(
            model_name='taniltsuulga',
            name='quality',
            field=models.ImageField(blank=True, null=True, upload_to='taniltsuulga', verbose_name='Чанар'),
        ),
    ]
