# Generated by Django 3.1 on 2020-11-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_advice_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advice',
            options={'ordering': ['-created_on'], 'verbose_name': 'Зөвлөгөө', 'verbose_name_plural': 'Зөвлөгөө'},
        ),
        migrations.AlterModelOptions(
            name='advicecategory',
            options={'ordering': ['-title'], 'verbose_name': 'Зөвөлгөөний ангиллал', 'verbose_name_plural': 'Зөвөлгөөний ангиллал'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['position'], 'verbose_name': 'Баннер зураг'},
        ),
        migrations.AlterModelOptions(
            name='counter',
            options={'ordering': ['position'], 'verbose_name': 'Тоолуур'},
        ),
        migrations.AlterModelOptions(
            name='featuredproduct',
            options={'ordering': ['title'], 'verbose_name': 'Танилцуулга бүтээгдэхүүн'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['title'], 'verbose_name': 'Зурагын сан'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-position'], 'verbose_name': 'Хамтрагч байгуулгын зураг'},
        ),
        migrations.AlterModelOptions(
            name='testimonail',
            options={'verbose_name': 'Үйлвэртэй танилцсан сэтгэгдэл', 'verbose_name_plural': 'Үйлвэртэй танилцсан сэтгэгдэл'},
        ),
        migrations.AlterField(
            model_name='bannervideo',
            name='src',
            field=models.CharField(max_length=255, verbose_name='Баннер бичлэг'),
        ),
    ]
