# Generated by Django 3.1 on 2021-08-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210825_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannervideo',
            options={'verbose_name': 'Нүүр хуудас - Баннер бичлэг'},
        ),
    ]
