# Generated by Django 3.1 on 2021-08-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20210826_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(max_length=550, null=True, verbose_name='Линк'),
        ),
        migrations.AddField(
            model_name='banner',
            name='link_text',
            field=models.CharField(max_length=550, null=True, verbose_name='Линк орох тэкст'),
        ),
    ]
