# Generated by Django 3.2.7 on 2021-10-03 11:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20210826_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='banneraboutus',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='banneraboutus',
            name='link',
            field=models.CharField(max_length=550, null=True, verbose_name='Линк'),
        ),
        migrations.AddField(
            model_name='banneraboutus',
            name='link_text',
            field=models.CharField(max_length=550, null=True, verbose_name='Линк орох тэкст'),
        ),
        migrations.AddField(
            model_name='banneraboutus',
            name='title',
            field=models.CharField(max_length=550, null=True, verbose_name='Гарчиг'),
        ),
        migrations.AddField(
            model_name='hrbanner',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='hrbanner',
            name='link',
            field=models.CharField(max_length=550, null=True, verbose_name='Линк'),
        ),
        migrations.AddField(
            model_name='hrbanner',
            name='link_text',
            field=models.CharField(max_length=550, null=True, verbose_name='Линк орох тэкст'),
        ),
        migrations.AddField(
            model_name='hrbanner',
            name='title',
            field=models.CharField(max_length=550, null=True, verbose_name='Гарчиг'),
        ),
    ]
