# Generated by Django 3.2.7 on 2021-10-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20211003_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneraboutus',
            name='link',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Линк'),
        ),
        migrations.AlterField(
            model_name='banneraboutus',
            name='link_text',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Линк орох тэкст'),
        ),
        migrations.AlterField(
            model_name='banneraboutus',
            name='title',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Гарчиг'),
        ),
        migrations.AlterField(
            model_name='hrbanner',
            name='link',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Линк'),
        ),
        migrations.AlterField(
            model_name='hrbanner',
            name='link_text',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Линк орох тэкст'),
        ),
        migrations.AlterField(
            model_name='hrbanner',
            name='title',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Гарчиг'),
        ),
    ]
