# Generated by Django 3.2.7 on 2021-10-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20211003_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Гарчиг')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='hrcard', verbose_name='Зураг')),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Хүний нөөц - Сонгон шалгаруулалт',
                'verbose_name_plural': 'Хүний нөөц - Сонгон шалгаруулалт',
                'ordering': ['position'],
            },
        ),
    ]
