# Generated by Django 3.2.7 on 2021-11-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_hrcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrcard',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='hrcard', verbose_name='Зураг'),
        ),
    ]
