# Generated by Django 3.1 on 2020-08-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='Админ', max_length=255, verbose_name='Created by'),
        ),
    ]
