# Generated by Django 3.1 on 2020-09-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200824_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_type',
            field=models.CharField(choices=[('news', 'News')], default='news', max_length=255),
        ),
    ]
