# Generated by Django 3.1 on 2020-09-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200916_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'News category', 'verbose_name_plural': 'News category'},
        ),
    ]
