# Generated by Django 3.1 on 2020-09-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200922_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_mn', models.CharField(max_length=250, verbose_name='Гарчиг')),
                ('video_type', models.IntegerField(choices=[(1, 'Видео'), (2, 'Нэвтрүүлэг')])),
                ('embed', models.TextField(verbose_name='ЭМБЭД код ')),
            ],
        ),
    ]
