# Generated by Django 3.1 on 2020-09-24 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Video news title')),
                ('video', models.FileField(upload_to='media/videonews')),
                ('youtube_url', models.CharField(max_length=500, verbose_name='Youtube video embed url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video news',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoNewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Video news category')),
            ],
            options={
                'verbose_name': 'Video news category',
                'ordering': ['category_name'],
            },
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
        migrations.AddField(
            model_name='videonews',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.videonewscategory'),
        ),
    ]
