# Generated by Django 3.1 on 2020-11-03 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200928_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_on'], 'verbose_name': 'Мэдээ', 'verbose_name_plural': 'Мэдээ'},
        ),
        migrations.AlterField(
            model_name='news',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
    ]
