# Generated by Django 3.1 on 2020-11-05 08:06

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20201103_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'News category', 'verbose_name_plural': 'News categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_on'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='Админ', max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Тэкст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='News slug'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
