# Generated by Django 3.1 on 2020-11-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20201105_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='videonews',
            name='description',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Short description'),
        ),
    ]
