# Generated by Django 3.1 on 2020-11-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_videonews_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='videonews',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
