# Generated by Django 3.2.7 on 2021-12-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20211203_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_mn',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_mn',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_mn',
        ),
        migrations.AddField(
            model_name='videonews',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
