# Generated by Django 3.1 on 2020-12-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Хариултууд', 'verbose_name_plural': 'Хариултууд'},
        ),
        migrations.AlterModelOptions(
            name='mcqquestion',
            options={'verbose_name': 'Асуултууд', 'verbose_name_plural': 'Асуултууд'},
        ),
    ]
