# Generated by Django 3.1 on 2020-12-17 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('cate_type', models.CharField(choices=[('энгийн', 'Энгийн')], default='энгийн', max_length=255)),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Prodcut categories ',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=255, verbose_name='ProductForm ')),
            ],
            options={
                'verbose_name': 'ProductForm',
                'ordering': ['form_name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, verbose_name='Type of product')),
            ],
            options={
                'verbose_name': 'Type of product',
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True, verbose_name='Бүтээгдэхүүн дотоод код')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product name ')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Product Slug')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тайлбар')),
                ('instructions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заавар')),
                ('ingredients', models.CharField(blank=True, max_length=500, null=True, verbose_name='Product ingredients')),
                ('warnings', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Warning')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/product/image/', verbose_name='Picture')),
                ('is_product_new', models.BooleanField(blank=True, default=False, null=True)),
                ('international_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product intertational name')),
                ('link', models.CharField(blank=True, max_length=355, null=True, verbose_name='Link to emonos')),
                ('daatgal', models.BooleanField(blank=True, default=False, help_text='Бүтээгдэхүүн даатгалд хамрагддаг бол зөв болгоно уу', null=True)),
                ('jor', models.BooleanField(blank=True, default=False, help_text='Бүтээгдэхүүн жортой бол зөвлөн үү', null=True)),
                ('productForm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productform', verbose_name='ProductForm')),
                ('producttype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.type', verbose_name='producttype')),
                ('web_category', models.ForeignKey(blank=True, db_column='web_category_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productcategory', verbose_name='Ангилал')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Prodcuts',
                'ordering': ['name'],
            },
        ),
    ]
