# Generated by Django 3.0.8 on 2020-07-22 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('cate_type', models.CharField(choices=[('энгийн', 'Энгийн'), ('зүрх судас', 'Зүрх судас'), ('витамин', 'Витамин'), ('хүүхэд', 'Хүүхэд')], default='энгийн', max_length=255)),
            ],
            options={
                'verbose_name': 'Бүтээгдэхүүний ангиллал',
                'verbose_name_plural': 'Бүтээгдэхүүнүүдийн ангиллал',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Product id')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Product name ')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Product Slug')),
                ('ingredients', models.CharField(max_length=500, verbose_name='Product ingredients')),
                ('suggest', models.CharField(max_length=1000, verbose_name='How to use ')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('image', models.ImageField(upload_to='media/product/image/', verbose_name='Picture')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='product.ProductCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Бүтээгдэхүүн',
                'verbose_name_plural': 'Бүтээгдэхүүн',
                'ordering': [],
            },
        ),
    ]
