# Generated by Django 3.0.8 on 2020-07-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='₮', max_length=150, verbose_name='Price'),
        ),
    ]
