# Generated by Django 3.1 on 2021-06-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='photo',
        ),
    ]
