# Generated by Django 3.1 on 2020-12-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='cate_type',
            field=models.CharField(choices=[('1', 'Эм'), ('2', 'Эмн.Тусламж'), ('3', 'Амин дэм'), ('4', 'Гоо сайхан'), ('5', 'Ээж ба хүүхэд'), ('6', 'Хүнс'), ('7', 'Өргөн хэрэглээ')], default='энгийн', max_length=255),
        ),
    ]
