# Generated by Django 3.1 on 2020-12-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201217_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
