# Generated by Django 3.1 on 2021-08-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210823_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Үнэ'),
        ),
    ]
