# Generated by Django 3.2.7 on 2021-12-03 06:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='instructions_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='international_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product intertational name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product name '),
        ),
        migrations.AddField(
            model_name='product',
            name='warnings_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Нэр'),
        ),
        migrations.AddField(
            model_name='productform',
            name='form_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ProductForm '),
        ),
        migrations.AddField(
            model_name='type',
            name='type_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Type of product'),
        ),
    ]
