# Generated by Django 3.0.8 on 2020-07-28 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200723_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': [], 'verbose_name': 'Product', 'verbose_name_plural': 'Prodcuts'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['title'], 'verbose_name': 'Product category', 'verbose_name_plural': 'Prodcut categories '},
        ),
    ]
