# Generated by Django 3.1 on 2020-12-17 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_category_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'Бүтээгдэхүүний ангилал', 'verbose_name_plural': 'Бүтээгдэхүүний ангилал'},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='cate_type',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='title',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Нэр'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.productcategory', verbose_name='Толгой ангилал'),
        ),
    ]
