# Generated by Django 3.0.8 on 2020-07-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200728_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_product_new',
            field=models.BooleanField(default=False),
        ),
    ]
