# Generated by Django 3.2.7 on 2021-12-03 07:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211203_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_mn',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_mn',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='instructions_mn',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='international_name_mn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product intertational name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_mn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product name '),
        ),
        migrations.AddField(
            model_name='product',
            name='warnings_mn',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_mn',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Нэр'),
        ),
        migrations.AddField(
            model_name='productform',
            name='form_name_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='ProductForm '),
        ),
        migrations.AddField(
            model_name='type',
            name='type_name_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='Type of product'),
        ),
    ]
