# Generated by Django 3.1 on 2020-12-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_category_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Бүтээгдэхүүний ангилал', 'verbose_name_plural': 'Бүтээгдэхүүний ангилал'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Product ingredients'),
        ),
        migrations.AlterField(
            model_name='product',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Заавар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warnings',
            field=models.TextField(blank=True, null=True, verbose_name='Warning'),
        ),
    ]
