# Generated by Django 3.0.8 on 2020-08-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_is_product_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_on'], 'verbose_name': 'Product', 'verbose_name_plural': 'Prodcuts'},
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(max_length=355, null=True, verbose_name='Link to emonos'),
        ),
    ]
