# Generated by Django 3.1 on 2020-12-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201218_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Бүтээгдэхүүн', 'verbose_name_plural': 'Бүтээгдэхүүн'},
        ),
        migrations.AlterModelOptions(
            name='productform',
            options={'ordering': ['form_name'], 'verbose_name': 'Бүтээгдэхүүний хэлбэр'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['type_name'], 'verbose_name': 'Бүтээгдэхүүний төрөл'},
        ),
    ]
