# Generated by Django 3.1 on 2020-09-15 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200911_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_name', models.CharField(max_length=255, verbose_name='Classification type')),
            ],
            options={
                'verbose_name': 'Classification',
                'ordering': ['classification_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=255, verbose_name='ProductForm ')),
            ],
            options={
                'verbose_name': 'ProductForm',
                'ordering': ['form_name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, verbose_name='Type of product')),
            ],
            options={
                'verbose_name': 'Type of product',
                'ordering': ['type_name'],
            },
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='cate_type',
            field=models.CharField(choices=[('энгийн', 'Энгийн')], default='энгийн', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='classification',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.classification', verbose_name='Classification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='productForm',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.productform', verbose_name='ProductForm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='producttype',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.type', verbose_name='producttype'),
            preserve_default=False,
        ),
    ]
