# Generated by Django 3.1 on 2020-09-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200915_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='international_name',
            field=models.CharField(default='', max_length=255, verbose_name='Product intertational name'),
            preserve_default=False,
        ),
    ]
