# Generated by Django 3.1 on 2020-09-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_international_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='daatgal',
            field=models.BooleanField(default=False, help_text='Бүтээгдэхүүн даатгалд хамрагддаг бол зөв болгоно уу'),
        ),
        migrations.AddField(
            model_name='product',
            name='jor',
            field=models.BooleanField(default=False, help_text='Бүтээгдэхүүн жортой бол зөвлөн үү'),
        ),
    ]
