# Generated by Django 3.1 on 2020-09-25 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200915_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.classification', verbose_name='Classification'),
        ),
    ]
