# Generated by Django 3.1 on 2020-09-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200925_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='classification',
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
    ]
