# Generated by Django 3.1 on 2020-09-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Бүтээгдэхүүн дотоод код'),
        ),
    ]
