# Generated by Django 3.1 on 2020-09-21 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('register', models.CharField(max_length=50, verbose_name='Register')),
                ('district', models.CharField(max_length=50, verbose_name='District')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Organization name')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('license_number', models.CharField(max_length=50, verbose_name='License number ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Activation',
        ),
    ]
