# Generated by Django 3.1 on 2020-12-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pharmaprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmaprofile',
            options={'verbose_name': 'Эм зүйч', 'verbose_name_plural': 'Эм зүйч'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Эмч', 'verbose_name_plural': 'Эмч'},
        ),
    ]
