# Generated by Django 3.0.8 on 2020-08-11 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20200811_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='poll',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='poll',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.Question'),
        ),
    ]
