# Generated by Django 3.0.8 on 2020-08-11 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20200811_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='poll',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='poll.Poll'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='poll.Answer'),
            preserve_default=False,
        ),
    ]
