# Generated by Django 3.0.8 on 2020-08-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20200811_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_answer_right',
            field=models.BooleanField(default=False, verbose_name='Is answer right'),
        ),
        migrations.DeleteModel(
            name='Right',
        ),
    ]
