# Generated by Django 3.0.8 on 2020-08-11 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20200811_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poll',
            new_name='Polls',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='poll',
            new_name='polls',
        ),
    ]
