# Generated by Django 3.0.8 on 2020-08-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20200811_1307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Polls',
            new_name='Poll',
        ),
    ]
