# Generated by Django 3.0.8 on 2020-08-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_auto_20200811_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='point',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
