# Generated by Django 3.0.8 on 2020-08-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_answer_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
