# Generated by Django 3.0.8 on 2020-08-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_auto_20200811_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='polls',
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='poll.Poll'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='poll.Question'),
        ),
    ]
