# Generated by Django 3.0.8 on 2020-08-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_auto_20200811_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.CharField(default=0, max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
