# Generated by Django 3.0.8 on 2020-08-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0016_auto_20200812_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_corret',
            field=models.BooleanField(default=False),
        ),
    ]
