# Generated by Django 3.0.8 on 2020-08-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0017_auto_20200812_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='poll',
            name='success_text',
            field=models.TextField(blank=True, help_text='Displayed if user passes.', verbose_name='Success Text'),
        ),
    ]
