# Generated by Django 3.0.8 on 2020-08-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0018_auto_20200818_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='success_text',
        ),
        migrations.AlterField(
            model_name='poll',
            name='slug',
            field=models.SlugField(default='', verbose_name='Slug '),
            preserve_default=False,
        ),
    ]
