# Generated by Django 3.1 on 2020-11-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0019_auto_20200821_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
    ]
